#!/usr/bin/env python3
"""
Session Health Check — validates Playwright browser sessions before use.

Currently checks: Twitter/X (the only Playwright-based posting skill).
If a session is expired, writes a WARNING_*.md to vault/Needs_Action/ so the
planning engine surfaces it on the Dashboard and the human is notified.

Usage:
    python scripts/check_sessions.py --vault ./vault
    python scripts/check_sessions.py --vault ./vault --session-path ~/.sessions/twitter

Exit codes:
    0 — all checked sessions are valid
    1 — one or more sessions are expired or unreachable

Recommended: run via PM2 at startup, or add to cron:
    @reboot python /path/to/scripts/check_sessions.py --vault /path/to/vault
    0 */6 * * * python /path/to/scripts/check_sessions.py --vault /path/to/vault
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    from dotenv import load_dotenv
    _PROJECT_DIR = Path(__file__).resolve().parents[1]
    load_dotenv(_PROJECT_DIR / ".env")
except ImportError:
    pass

try:
    from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeout
except ImportError:
    sys.exit("Missing dependency. Run:  pip install playwright && playwright install chromium")

_DEFAULT_SESSION = Path(os.environ.get("TWITTER_SESSION_PATH", "~/.sessions/twitter")).expanduser()
_HOME_URL = "https://x.com/home"


def _ts() -> str:
    return datetime.now(timezone.utc).isoformat()


def _write_warning(vault: Path, service: str, detail: str) -> Path:
    """Write a WARNING_*.md to vault/Needs_Action/ for the human to act on."""
    now = datetime.now(timezone.utc)
    name = f"WARNING_{service.upper()}_SESSION_EXPIRED_{now.strftime('%Y%m%d_%H%M%S')}.md"
    content = f"""\
---
type: alert
priority: high
source: check-sessions
service: {service}
created: {now.isoformat()}
status: pending
---

# {service.upper()} Session Expired

The Playwright browser session for **{service}** is no longer valid.
Automated {service} posts will fail until the session is renewed.

**Detail:** {detail}
**Detected:** {now.strftime('%Y-%m-%d %H:%M UTC')}

## Required Action

Re-authenticate the {service} session:

```bash
python watchers/auth_{service.lower()}.py
```

Move this file to `/Done` after re-authentication is complete.

*Generated by check_sessions.py*
"""
    alert_path = vault / "Needs_Action" / name
    alert_path.parent.mkdir(parents=True, exist_ok=True)
    alert_path.write_text(content, encoding="utf-8")
    return alert_path


def check_twitter_session(session_path: Path, vault: Path) -> bool:
    """
    Launch a headless browser with the stored Twitter session and verify login.
    Returns True if session is valid, False if expired.
    """
    if not session_path.exists():
        print(f"  [TWITTER] Session directory not found: {session_path}")
        alert = _write_warning(vault, "twitter",
                               f"Session directory not found: {session_path}")
        print(f"  [TWITTER] ⚠ Warning written → {alert.name}")
        return False

    print(f"  [TWITTER] Checking session at {session_path} …")
    try:
        with sync_playwright() as p:
            context = p.chromium.launch_persistent_context(
                str(session_path),
                headless=True,
                args=["--disable-blink-features=AutomationControlled"],
                viewport={"width": 1280, "height": 800},
            )
            page = context.pages[0] if context.pages else context.new_page()
            try:
                page.goto(_HOME_URL, wait_until="domcontentloaded", timeout=30_000)
                page.wait_for_timeout(2000)

                current_url = page.url
                if any(kw in current_url for kw in ("login", "signin", "i/flow")):
                    detail = f"Redirected to {current_url} — session cookie expired"
                    print(f"  [TWITTER] ✗ Session expired ({current_url})")
                    alert = _write_warning(vault, "twitter", detail)
                    print(f"  [TWITTER] ⚠ Warning written → {alert.name}")
                    return False

                print(f"  [TWITTER] ✓ Session valid (on {current_url})")
                return True

            except PlaywrightTimeout as exc:
                detail = f"Navigation timeout: {exc}"
                print(f"  [TWITTER] ✗ {detail}")
                _write_warning(vault, "twitter", detail)
                return False
            finally:
                context.close()

    except Exception as exc:
        detail = f"Playwright error: {exc}"
        print(f"  [TWITTER] ✗ {detail}")
        _write_warning(vault, "twitter", detail)
        return False


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Check Playwright browser session validity and alert if expired."
    )
    parser.add_argument("--vault", default="./vault",
                        help="Path to Obsidian vault (default: ./vault)")
    parser.add_argument("--session-path", default=str(_DEFAULT_SESSION),
                        help=f"Path to Twitter session (default: {_DEFAULT_SESSION})")
    parser.add_argument("--json", action="store_true",
                        help="Output result as JSON")
    args = parser.parse_args()

    vault = Path(args.vault).expanduser().resolve()
    session_path = Path(args.session_path).expanduser().resolve()

    print("Session Health Check")
    print("=" * 40)

    results = {}
    all_ok = True

    twitter_ok = check_twitter_session(session_path, vault)
    results["twitter"] = "valid" if twitter_ok else "expired"
    if not twitter_ok:
        all_ok = False

    print("=" * 40)
    print(f"Result: {'ALL OK' if all_ok else 'ONE OR MORE SESSIONS EXPIRED'}")

    if args.json:
        print(json.dumps({"timestamp": _ts(), "sessions": results, "all_ok": all_ok}, indent=2))

    sys.exit(0 if all_ok else 1)


if __name__ == "__main__":
    main()
